#!/bin/bash
set -e
if [ $# -eq 0 ]
then
    echo "usage: $0 <shippable username>"
    exit 1
fi
sshkeyfiles=$(ssh-add -l |awk '{print $3}')
for sshkeyfile in $sshkeyfiles
do
    if openssl rsautl -decrypt -inkey $sshkeyfile -in etc/secrets/key.$1 -out secret.key
    then
        openssl aes-256-cbc -d -in etc/secrets/shippable.env.$1.encrypted -pass file:secret.key
        rm secret.key
        exit
    fi
done
