#!/bin/bash
set -e
if [ $# -eq 0 ]
then
    echo "usage: $0 <shippable username>"
    exit 1
fi
openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in etc/secrets/key.$1 -out secret.key
openssl aes-256-cbc -d -in etc/secrets/shippable.env.$1.encrypted -pass file:secret.key
rm secret.key
