#!/bin/bash
set -xe
if [ -z "$KEYSTORE" ]; then
	echo "KEYSTORE variable missing, set it to the place of keystore file to be generated"
	exit 1
fi
if [ -z "$KEYSTOREPASS" ]; then
	echo "KEYSTOREPASS variable missing, set it to the passphrase of the generated keystore"
	exit 1
fi

KEYSTOREDIR=$(dirname "$KEYSTORE")
KEYSTOREFILE=$(basename "$KEYSTORE")
if [ ! -f "$KEYSTOREFILE" ]
then
  TMP=$(mktemp -d)
  cd $TMP
  SUBJ="/C=HU/ST=Pest/L=Hungary/O=Kozossegi Digitalis Eszkozok Alapitvany/OU=Org/CN=*.demokracia.rulez.org"
  ALIAS="PDEngineKeys"
  PRIVKEYFILE=selfsigned.key
  CERTFILE=selfsigned.crt
  openssl req -x509 -newkey rsa:2048 -keyout $PRIVKEYFILE -out $CERTFILE -days 365 -nodes -subj "$SUBJ"
  openssl pkcs12 -name "$ALIAS" -export -in $CERTFILE -inkey $PRIVKEYFILE -out "$KEYSTOREFILE" -passout pass:"$KEYSTOREPASS"
  sudo mkdir -p "$KEYSTOREDIR"
  sudo cp $KEYSTOREFILE "$KEYSTOREDIR/"
  sudo chmod og-w "$KEYSTOREDIR"
  sudo chown $USER "$KEYSTORE"
  sudo chmod og-r-w-x "$KEYSTORE"
  rm -r $TMP
fi
