#!/bin/bash

if [ $# -eq 0 ]
then
    echo "usage: $0 <shippable username>"
    echo "expects the ssh pubkey at ~/.ssh/shippable.<shippable username>.pub"
    exit 1
fi
set -xe
mkdir -p ~/tmp
KEYFILE=etc/secrets/key.$1
PASSFILE=~/tmp/secret.data
openssl rand 192 -out $PASSFILE
openssl aes-256-cbc -in ~/.ssh/shippable.PDEngine.env -out etc/secrets/shippable.env.$1.encrypted -pass file:$PASSFILE
openssl rsautl -encrypt -pubin -inkey <(ssh-keygen -e -f ~/.ssh/shippable.$1.pub -m PKCS8) -in $PASSFILE -out $KEYFILE
rm -f $PASSFILE
