#!/bin/bash
set -x
KEYSTOREDIR=/pdengine/src/main/resources
KEYSTOREFILE=keystore.pk12
mkdir -p $KEYSTOREDIR
cd $KEYSTOREDIR || exit 1
if [ ! -f "$KEYSTOREFILE" ]
then
  SUBJ="/C=HU/ST=Pest/L=Hungary/O=Kozossegi Digitalis Eszkozok Alapitvany/OU=Org/CN=*.demokracia.rulez.org"
  KEYSTOREPASS="changeit"
  ALIAS="PDEngineKeys"
  PRIVKEYFILE=selfsigned.key
  CERTFILE=selfsigned.crt
  openssl req -x509 -newkey rsa:2048 -keyout $PRIVKEYFILE -out $CERTFILE -days 365 -nodes -subj "$SUBJ"
  openssl pkcs12 -name "$ALIAS" -export -in $CERTFILE -inkey $PRIVKEYFILE -out $KEYSTOREFILE -passout pass:"$KEYSTOREPASS"
  rm $PRIVKEYFILE $CERTFILE
  chmod og-r-w-x $KEYSTOREFILE 
fi
