#!/bin/bash
rsync -e "ssh -p 22022" -ar shippable/ shippable@demokracia.rulez.org:/var/www/adadocs/PDEngine/$BUILD_NUMBER
normalized_branch=$(echo $BRANCH|sed 'sA[/_]A.Ag')
ln -s $normalized_branch $BUILD_NUMBER
rsync -e "ssh -p 22022" -a $normalized_branch shippable@demokracia.rulez.org:/var/www/adadocs/PDEngine

