#!/bin/bash
set -e
echo Dsonar.github.oauth=$GITHUB_OAUTH
if [ $PULL_REQUEST != false ]
then
    mvn sonar:sonar -Dsonar.organization=edemo -Dsonar.github.pullRequest=$PULL_REQUEST -Dsonar.analysis.mode=preview -Dsonar.github.oauth=$GITHUB_OAUTH
fi
