server:
  port: 8080
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: changeit
    key-alias: PDEngineKeys
    key-password: changeit

spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
spring:
  profiles:
    active:
    - integration-test
